---
date: "July 10, 2024"
date-modified: last-modified
---

# American Community Survey (5 Year Estimates) {.unnumbered}

## Brief Description

The American Community Survey (ACS) provides detailed demographic, social, economic, and housing data based on 5-year estimates. This dataset includes various measures related to community capitals, such as housing, employment, commuting, and broadband subscription.

## Source

The primary source for the measures below is the ACS 5-year report, 2022.

## Measures

### Margins of Error

Most of the ACS measures and datasets have the high_moe columns which is True if the margin of error is greater than half of the measure.

### Percent of households with own children that are single-parent households (Social)

#### Measure Description

This indicator measures the percentage of households headed by a single parent (male or female) with their own children under 18 and no spouse present. It is calculated by dividing the total number of such households by total households. A higher percentage of single-parent households may signal increased vulnerability in a community. These households often face greater financial stress, limited social support, and reduced capacity to respond to and recover from disasters. These challenges can negatively affect social capital and community resilience (Flanagan et al., 2011).
#### Source

ACS Variables:

-   S1101_C03_005
    -   Male householder, no spouse present, family household. Households with own children of the householder under 18 years.
-   S1101_C04_005
    -   Female householder, no spouse present, family household. Households with own children of the householder under 18 years.
-   S1101_C01_005
    -   Total householders. Households with own children of the householder under 18 years.

#### Calculation

$$\text{prop\_single} = \frac{\text{Male + Female}}{\text{Total Household}}$$

### Percent of all households with own children that are Female single-parent households (Social)

#### Source

ACS Variables:

-   S1101_C04_005
    -   Female householder, no spouse present, family household. Households with own children of the householder under 18 years.
-   S1101_C01_005
    -   Total householders. Households with own children of the householder under 18 years.

#### Measure Description & Calculation

The proportion of female single-parent households is calculated by summing the number of female single-parent households and dividing by the total number of households.

$$\text{prop\_female\_single\_parent} = \frac{\text{Female}}{\text{Total Household}}$$

### Percent of all households with own children that are Male single-parent households (Social)

#### Source

ACS Variables:

-   S1101_C03_005
    -   Male householder, no spouse present, family household. Households with own children of the householder under 18 years.
-   S1101_C01_005
    -   Total householders. Households with own children of the householder under 18 years.

#### Measure Description & Calculation

The proportion of male single-parent households is calculated by summing the number of male single-parent households and dividing by the total number of households.

$$\text{prop\_male\_single\_parent} = \frac{\text{Male}}{\text{Total Household}}$$

### Percent of Workers with more than an hour commute (Social)

#### Measure Description

This indicator measures the share of workers aged 16 and older (excluding those who work from home) who commute more than one hour to their place of work. Long commutes are associated with reduced time and energy for civic engagement, local social connections, and participation in community life. Research suggests that extended commute times can negatively impact social capital by limiting individuals’ availability for volunteerism, neighborhood interaction, and community-based activities. These patterns may also affect workforce well-being and local economic vibrancy by decreasing worker satisfaction and retention (Besser et al., 2008).

#### Source

ACS Variables:

-   B08134_010 (# long-distance Commuters)
-   B08134_001 (total commuters)

#### Calculation

$$\text{percent\_long\_commute} = \frac{\text{Long-distance commuters}}{\text{Total Commuters}}$$

### English Proficiency (Social)

#### Measure Description

This indicator measures the proportion of residents who speak English "very well" or better, calculated by dividing the number of proficient English speakers by the total population. English proficiency is an essential component of a community’s ability to access information and services. Limited English proficiency can create barriers to health care, education, employment, and emergency communication. It is also a key component of social vulnerability in disaster contexts. Communities with a higher proportion of residents who speak English less than very well are more likely to experience adverse outcomes during emergencies due to difficulties understanding warnings, evacuation orders, and recovery information. Identifying these communities can support targeted interventions and improve resilience (Flanagan et al., 2011).

#### Source

ACS Variables for residents who speak very good English:

-   B06007_001
    -   Residents who are proficient in speaking English
-   B06007_002
    -   Residents that only speak English
-   B06007_004
    -   Residents that speak Spanish at home and speak English "very well"
-   B06007_007 (Residents that speak other languages at home and speak English "very well")

#### Calculation

$$\text{percent\_english\_proficiency} = \frac{\text{Sum Proficient}}{\text{Total Residents}}$$

### Employments in agriculture, forestry, fishing, hunting, and mining (Natural)

#### Measure Description

This indicator measures the share of the civilian employed population working in agriculture, forestry, fishing, hunting, and mining industries. These industries, while important to rural economies, can be associated with lower levels of economic resilience. Natural resource dependence in rural counties is linked to decreased economic prosperity. Such communities often experience reduced investment in both individual and community human capital, including limited educational and workforce development opportunities. Overreliance on resource-based employment may also constrain long-term financial capital growth due to economic volatility and lower-wage job structures. (Mueller, 2020)

#### Source

ACS Variables:

-   C24070_001
    -   Total civilian employed population 16 years or older.
-   C24070_002
    -   Total civilian employed population 16 years or older in agriculture, forestry, fishing and hunting, and mining.

#### Calculation

$$\text{prop\_employed} = \frac{\text{Agriculture, forestry, fishing and hunting, and mining Employments}}{\text{Total Employments}}$$

### Median household property value (Built)

#### Source

ACS Variables:

-   DP04_0089
    -   Mortgage status for owner-occupied units

#### Measure Description & Calculation

Median Household Value of Owner Occupied Units. The median household property value is directly taken from the ACS 5-year report, variable B25077_001.

### Median year of built structures (Built)

#### Source

ACS Variables:

-   B25035_001 (Median year of built structures)

#### Measure Description & Calculation

The median year of built structures is directly taken from the ACS 5-year report, variable B25035_001.

### Percentage of housing units built before 1960 (Built)

#### Measure Description & 
This indicator measures the share of the population aged 25 and older who have earned a bachelor’s degree or higher. Higher education is a key driver of human and financial capital, contributing to innovation, income growth, and civic engagement. Research shows that skilled workers not only support economic growth but also influence policy decisions and increase demand for amenities and public goods. These dynamics can improve community quality of life, helping attract and retain additional high-skill workers, which in turn reinforces local prosperity (Fan et al., 2016).

#### Source

ACS Variables:

-   B25034_010 (Housing units built 1940 to 1949)
-   B25034_009 (Housing units built 1950 to 1959)
-   B25034_011 (Housing units built before 1940)
-   B25034_001 (Total housing units)

#### Calculation

The proportion of housing units built before 1960 is calculated by summing the housing units built up to 1959 and dividing by the total number of housing units.

### Percentage of occupied housing units (Built)

#### Measure Description

This indicator measures the share of occupied housing units, reflecting the level of property utilization in a community. Vacant and abandoned properties are often signs of disinvestment in the built environment and are associated with physical deterioration, increased crime, and reduced neighborhood vitality. As detailed by Roude et al. (2024), such vacancies can erode social ties, diminish perceived safety, and discourage economic activity. In contrast, higher occupancy supports financial capital through property value retention, fosters social capital via community engagement, and sustains the built environment as a foundation for well-being (Roude et al., 2024).

#### Source

ACS Variables:

-   DP04_0002P
    -   Percent of Occupied housing units

#### Calculation

The proportion of occupied housing units is calculated by the percent of occupied units.

### Percentage of households with complete plumbing (Built)

#### Source

ACS Variables:

-   B25047_002 (# Facilities with complete plumbing)
-   B25047_001 (Total plumbing facilities)

#### Measure Description & Calculation

The proportion of households with complete plumbing is calculated by dividing the number of facilities with complete plumbing by the total number of plumbing facilities.

$$\text{prop\_plumbing} = \frac{\text{Complete Plumbing}}{\text{Total Plumbing}}$$

### Percentage of households with a broadband subscription (Built)

#### Measure Description
This indicator measures the percentage of households with broadband internet subscriptions. Broadband is a key component of built capital that enables the development of human capital by supporting access to education, employment, and healthcare. According to Stritzel and LoPiccalo (2023), gaps in broadband availability—especially in rural areas—limit communities’ capacity to retain residents, attract employers, and foster income growth. Reliable internet is also essential for virtual learning and telehealth, both of which expand opportunities for individual advancement and community resilience (Valentín-Sívico et al., 2023).

#### Source

ACS Variables:

-   DP02_0154P
    -   Percent of total households with a broadband internet subscription

#### Calculation
The percent of households with a broadband subscription is calculated by DP02_0154P.

### Race Diversity (Cultural)

#### Source

ACS Variables:

-   B03002_003 (Not Hispanic or Latino:!!White alone)
-   B03002_004 (Not Hispanic or Latino:!!Black or African American alone)
-   B03002_005 (Not Hispanic or Latino:!!American Indian and Alaska Native alone)
-   B03002_006 (Not Hispanic or Latino:!!Asian alone)
-   B03002_007 (Not Hispanic or Latino:!!Native Hawaiian and Other Pacific Islander alone)
-   B03002_008 (Not Hispanic or Latino:!!Some other race alone)
-   B03002_009 (Not Hispanic or Latino:!!Two or more races)
-   B03002_013 (Hispanic or Latino:!!White alone)
-   B03002_014 (Hispanic or Latino:!!Black or African American alone)
-   B03002_015 (Hispanic or Latino:!!American Indian and Alaska Native alone)
-   B03002_016 (Hispanic or Latino:!!Asian alone)
-   B03002_017 (Hispanic or Latino:!!Native Hawaiian and Other Pacific Islander alone)
-   B03002_018 (Hispanic or Latino:!!Some other race alone)
-   B03002_019 (Hispanic or Latino:!!Two or more races)

#### Measure Description & Calculation

-   Diversity in the distribution of different race across Iowa communities.

#### Simpson Index

$$D = 1 - \left( \frac{\sum n(n-1)}{N(N-1)} \right)$$

Where:

• n = the total number of organisms of a particular species

• N = the total number of organisms of all species

Interpretation: Simpson's Diversity Index is a measure of diversity which takes into account the number of species present, as well as the relative abundance of each species. As species richness and evenness increase, so diversity increases. It is also the probability of picking two random individuals which are not of the same group.

#### Race Diversity

With different groups of race taken from ACS, we calculate the Simpson Index to measure the diversity, using the above formula.

### Health Insurance Coverage (Human)

#### Measure Description
This indicator measures the percentage of the population with health insurance. Lack of health insurance is associated with poorer health outcomes and higher mortality rates. Research shows that uninsured individuals often face significant barriers to essential care, particularly in managing chronic diseases. Uninsured patients with conditions like cancer, diabetes, and cardiovascular disease often have more advanced disease at diagnosis, receive lower-quality care, and experience higher mortality rates both during hospitalization and after discharge. Health insurance coverage improves access to preventive services and essential care, leading to better health outcomes (Woolhandler & Himmelstein, 2017).

#### Source

ACS Variables:

-   S2701_C03_001
    -   Percent of civilian non-institutionalized population with health insurance

#### Calculation

-   Measure taken directly from S2701_C03_001

### Bachelor's Degree Attainment (Human)

#### Measure Description

This indicator measures the share of the population aged 25 and older who have earned a bachelor’s degree or higher. Higher education is a key driver of human and financial capital, contributing to innovation, income growth, and civic engagement. Research shows that skilled workers not only support economic growth but also influence policy decisions and increase demand for amenities and public goods. These dynamics can improve community quality of life, helping attract and retain additional high-skill workers, which in turn reinforces local prosperity (Fan et al., 2016).

#### Source

ACS Variables:

-   S1501_C02_015
    -   Percent of 25+ population with at least a bachelor's degree

#### Calculation

-   Measure taken directly from S1501_C02_015

### High School Degree Attainment (Human)

#### Measure Description

This indicator measures the percentage of the population aged 25 and older who have completed a high school diploma or equivalent. Educational attainment at this level is a foundational component of human capital and supports workforce participation and local economic stability. Communities with higher education levels tend to experience faster employment growth. A better-educated population is more likely to engage in civic life, support public services, and contribute to a more adaptable and productive labor force (Fan et al., 2016).

#### Source

ACS Variables:

-   S1501_C02_014
    -   Percent of 25+ population with at least a high school degree (or equivalent)

#### Calculation

-   Measure taken directly from S1501_C02_014

### Senior Dependency Ratio (Human)

#### Source

ACS Variables:

-   S0101_C02_030
    -   Percent of population that is 65 years of age and over
-   S0101_C02_022
    -   Percent of population that is under 18 years of age

#### Measure Description & Calculation

$$\text{pct\_18\_64 = 100 - (pct\_under\_18\ +\ pct\_65\_plus)}$$ 
$$\text{dep\_ratio\_senior} = \frac{\text{pct\_65\_plus}}{\text{pct\_18\_64}}$$

### Child Dependency Ratio (Human)

#### Source

ACS Variables:

-   S0101_C02_030
    -   Percent of population that is 65 years of age and over
-   S0101_C02_022
    -   Percent of population that is under 18 years of age

#### Measure Description & Calculation

$$\text{pct\_18\_64 = 100 - (pct\_under\_18\ +\ pct\_65\_plus)}$$ 
$$\text{dep\_ratio\_child} = \frac{\text{pct\_under\_18}}{\text{pct\_18\_64}}$$

### Dependency Ratio (Human)

#### Source

ACS Variables:

-   S0101_C02_030
    -   Percent of population that is 65 years of age and over
-   S0101_C02_022
    -   Percent of population that is under 18 years of age

#### Measure Description & Calculation

$$\text{dep\_ratio} = \text{Senior Dependency Ratio + Child Dependency Ratio}$$

### Poverty Rate (Financial)

#### Source

ACS Variables:

-   S1701_C03_001
    -   Percent population for whom poverty status is determined with income below the federal poverty line in the last 12 months

#### Measure Description & Calculation

-   Measure taken directly from S1701_C03_001

### Labor Force Participation Rate (Population 16+) (Financial)

#### Measure Description
This indicator measures the percentage of the population aged 16 and older actively participating in the labor force. Lack of labor force participation in this group is associated with lower well-being and can lead to diminished human and financial capital. Research shows that individuals who are unemployed or out of the labor force report lower life satisfaction and higher negative affect. However, they tend to have a more optimistic outlook about their future. When individuals of this age group are not engaged in the labor force, they may experience reduced economic opportunities, impacting both their financial capital and overall life satisfaction (Graham & Pinto, 2021).

#### Source

ACS Variables:

-   S2301_C02_001
    -   Labor force participation rate for population 16 or older

#### Calculation

-   Measures taken directly from S2301_C02_001 and S2301_C02_021

### Labor Force Participation Rate (Population 20-64) (Financial)

#### Measure Description
This indicator measures the percentage of individuals aged 20 to 64 who are actively participating in the labor force. For this age group, lack of labor force participation is strongly tied to lower health outcomes and reduced human capital. Research indicates that people within this age range who are unemployed have significantly lower life satisfaction compared to those employed, though they remain optimistic about their future. The financial implications of unemployment for this group are considerable, as it reduces both income opportunities and social mobility, ultimately impacting their long-term economic stability (Graham & Pinto, 2021).

#### Source

ACS Variables:

-   S2301_C02_021
    -   Labor force participation rate for population aged 20 to 64

#### Calculation

-   Measures taken directly from S2301_C02_001 and S2301_C02_021

### Unemployment Rate (Financial)

#### Measure Description
This indicator measures the percentage of the population aged 16 and older who are unemployed. Unemployment is associated with both poorer psychological health and reduced financial capital. Research shows that unemployed individuals experience significantly more distress and lower well-being than those who are employed. Employment contributes to mental health by providing structure, social contact, purpose, and status; its absence often leads to deteriorated psychological well-being (Paul & Moser, 2009). Financially, unemployment can limit a household’s ability to maintain income and savings, contributing to greater economic vulnerability over time (Gruber, 2000).

#### Source

ACS Variables:

-   S2301_C04_001
    -   Unemployment rate for the population 16 or older

#### Calculation

-   Measure taken directly from S2301_C04_001

### Median Household Income (Financial)

#### Measure Description
This indicator measures the median income of households. Median household income is a key component of financial capital and is strongly associated with overall quality of life. Higher income levels provide individuals with better access to resources such as healthcare, education, and social opportunities, which in turn contribute to better physical and psychological well-being. Research has shown that individuals with higher incomes tend to report higher levels of life satisfaction across multiple dimensions, including physical health, mental well-being, and social engagement. According to a study on quality of life and sense of community, people with higher income report enhanced quality of life, including better psychological health and greater social connectedness (Gattino et al., 2013).

#### Source

ACS Variables:

-   S1903_C03_001
    -   Median income for all households in the past 12 months (2022 dollars)

#### Calculation

-   Measure taken directly from S1903_C03_001

### Households Below Poverty Level (Financial)

#### Measure Description

This indicator measures the percentage of households with income below the federal poverty level in the past 12 months. Poverty represents a constraint on financial capital, limiting access to essential goods, services, and investments that support economic stability and long-term mobility. Research shows that poverty is causally linked to poorer developmental outcomes in children, particularly in cognitive and educational domains, due to factors such as material hardship, family stress, and limited access to enriching environments (Chaudry & Wimer, 2016). At the household level, poverty reduces the ability to accumulate savings, invest in education or housing, and respond to financial shocks—core dimensions of financial capital (Chetty et al., 2014). The timing, duration, and concentration of poverty—especially in early childhood and across communities—can have lasting impacts on opportunity and economic well-being.

#### Source

ACS Variables:

- S1701_C03_001
    - Population for whom poverty status is determined in the past 12 months.

#### Calculation
-   Measure taken directly from S1701_C03_001

### Gini Index of Income Inequality (Financial)

#### Measure Description
This indicator measures income inequality within a population using the Gini coefficient, where higher values reflect greater disparity between high- and low-income earners. Income inequality can reduce overall child well-being, regardless of a household's individual income. Based on (Wilkinson & Pickett, 2007), greater inequality is associated with worse outcomes across multiple child well-being domains—including higher rates of teenage births, infant mortality, low birth weight, juvenile homicide, poor mental health, and school dropout. Societies with larger gaps between rich and poor tend to experience more widespread social and developmental challenges. These findings suggest that income distribution, not just income levels, influences the development of human and financial capital.

#### Source

ACS Variables:

-   B19083_001
    -   Gini index of income inequality

#### Calculation
-   Measure taken directly from B19083_001
