---
data: "2025-01-02"
date-modified: last-modified
---

# County Business Patterns {.unnumbered}

## Source
[County Business Patterns](https://www.census.gov/data/datasets/2022/econ/cbp/2022-cbp.html)

## Brief Description

County Business Patterns include data about the number and size of businesses at the county level, such as the count of businesses with certain ranges of employees. The data also includes aggregated payroll data for those businesses.

## Measures

### Percent of total businesses that are small (<=4 employees) (Financial)

#### Measure Description

This indicator measures the proportion of businesses within a community that have fewer than four employees. A higher percentage of such small businesses is often indicative of a robust entrepreneurial environment. Research demonstrates that communities with a greater concentration of small businesses tend to exhibit better population health outcomes. This relationship is attributed to the role of small businesses in enhancing social capital by fostering local networks, civic engagement, and collective efficacy. Small businesses also contribute to local economic development by creating jobs, retaining wealth within the community, and stimulating economic diversification (Blanchard et al., 2012).

#### Calculation

This measure is calculated as the number of businesses that are small (less than or equal to 4 employees) divided by the total number of businesses.

$${\text{pct\_small\_businesses =}}\frac{\text{small\_business\_count}}{\text{total\_business\_count}}$$




