---
date: "July 10, 2024"
date-modified: last-modified
---

# Cultural Capital {.unnumbered}

Description here

## Citations

Clift S. Creative arts as a public health resource: moving from practice-based research to evidence-based practice. Perspectives in Public Health. 2012;132(3):120-127. doi:10.1177/1757913912442269

Wilkinson, A.V., Waters, A.J., Bygren, L.O. et al. Are variations in rates of attending cultural activities associated with population health in the United States?. BMC Public Health 7, 226 (2007). https://doi.org/10.1186/1471-2458-7-226


## Measures

### Cultural Locations Per 10,000 Population

Historic sites, public art, museums, monuments

#### Source
[Iowa Culture App](https://www.dcaapp.com/) (website no longer active)

The total count of historic sites, museums, public art, monuments, and similar locations, collectively referred to as cultural locations was collected from the Iowa Culture App. To assess the distribution of these cultural sites within each city or county, we computed the number of cultural locations per 10,000 people. This measure allows us to compare the availability and density of cultural resources across different areas.

After extracting the relevant data from the website, we tallied the total number of cultural locations for each city or county. To calculate our measure of interest (Cultural_Locations_per_10k), we used the following steps:

-   Extracted city/county population data from the American Community Survey (ACS).
-   Divided the total number of cultural locations in each city/county by the population of the corresponding city/county.
-   Multiplied the results by 10,000 to express the number of cultural locations per 10,000 people.

The final measure Cultural_Locations_per_10k was obtained using this formula:

$$
\text{Cultural\_Locations\_per\_10k} = \frac{\text{Total Number of Cultural Locations}}{\text{Population}} \times 10,000
$$

### Library Visits per 10k

#### Source
[State Library of
Iowa](https://www.statelibraryofiowa.gov/application/files/5217/1623/2157/IOWA_PUBLIC_LIBRARY_STATISTICS_big_book_fy23_final.pdf)

State Library of Iowa provides statistics on income, expenditures, collections, circulation and other measures. It is split up by a cities size and name. We looked at the fiscal year 2023, which is July 1, 2022 - June 30, 2023.

The number of library visits per 10,000 people in a city.

$$
\text{Visits per 10k} = \frac{\text{Visits}}{\text{Population}}\times 10000
$$

