---
date: "07/11/2024"
date-modified: last-modified
---

# Federal Bureau of Investigations Crime Reports {.unnumbered}

## Brief Description

### Uniform Crime Reporting Program Data

The FBI Crime Reports dataset provides detailed information on various criminal activities across different counties. For our analysis, we primarily focused on violent offenses such mas murder, forcible rape, robbery, and aggravated assault. We calculated the crime rate per 10,000 people to understand the prevalence of these violent crimes in each county.

### Community Social Context FBI

The report provides property crime and violent crime data for cities and counties in Iowa. It provides the total number of property and violent crimes along with the property and violent crime rate per 10,000 people.

## Focusing on Violent Crimes

1.  Murder: 11(Non-negligent)
2.  Forcible Rape: 20
3.  Robbery: 30
4.  Aggravated Assault: 40

## Source

[Uniform Crime Reporting Program Data](https://www.icpsr.umich.edu/web/ICPSR/studies/38796) Community Social Context FBI City Data from 2005-2020 Community Social Context FBI County Data from 2005-2020

## Measures

### violentcrime (Social)

#### Measure Description & Calculation

-   Total number of violent crimes reported in 2020. Data was reported by the FBI for selected places and counties. County counts reflect the sum of all reported offenses from agencies within the county that submitted data to the FBI. The county count may not include all offenses if agencies within the county did not report or if reported figures did not comply with FBI reporting standards. Those places or counties either not reporting to the FBI or not complying with FBI reporting standards and, thus, not compiled by the FBI, are shown as having Insufficient Data in the map. FBI UCR data should not be compared across places or counties, and should not be compared from one year to another. For information on how PolicyMap assigned FBI data to map areas using a DOJ equivalency table, as the FBI does not provide geographic identifiers, see the Data Directory. PolicyMap last updated this data in February 2022.

### violentcrimert (Social)

#### Measure Description & Calculation

-   Total number of violent crimes reported per 100,000 people in 2020. PolicyMap divided the total number of violent crimes that were reported in a county or place by the population count provided by the FBI and multiplied that ratio by 100,000. The place population count is an estimate from the FBI. The county population count is an estimate of the number of people served by the agencies within the county that report offenses. Data was reported to the FBI for selected places and counties by the FBI. County counts reflect the sum of all reported offenses from agencies within the county that submitted data to the FBI. The county count may not include all offenses if agencies within the county did not report or if reported figures did not comply with FBI reporting standards. Those places or counties either not reporting to the FBI or not complying with FBI reporting standards and, thus, not compiled by the FBI, are shown as having Insufficient Data in the map. PolicyMap recommends consulting the Data Directory for more information on the data. PolicyMap last updated this data in February 2022.

### propertycrime (Social)

#### Measure Description & Calculation

-   Total number of property crimes reported in 2020. Data was reported by the FBI for selected places and counties. County counts reflect the sum of all reported offenses from agencies within the county that submitted data to the FBI. The county count may not include all offenses if agencies within the county did not report or if reported figures did not comply with FBI reporting standards. Those places or counties either not reporting to the FBI or not complying with FBI reporting standards and, thus, not compiled by the FBI, are shown as having Insufficient Data in the map. FBI UCR data should not be compared across places or counties, and should not be compared from one year to another. For information on how PolicyMap assigned FBI data to map areas using a DOJ equivalency table, as the FBI does not provide geographic identifiers, see the Data Directory. PolicyMap last updated this data in February 2022.

### propertyrt (Social)

#### Measure Description & Calculation

-   Total number of property crimes reported per 100,000 people in 2020. PolicyMap divided the total number of property crimes that were reported in a county or place by the population count provided by the FBI and multiplied that ratio by 100,000.The place population count is an estimate from the FBI. The county population count is an estimate of the number of people served by the agencies within the county that report offenses. Data was reported to the FBI for selected places and counties by the FBI. County counts reflect the sum of all reported offenses from agencies within the county that submitted data to the FBI. The county count may not include all offenses if agencies within the county did not report or if reported figures did not comply with FBI reporting standards. Those places or counties either not reporting to the FBI or not complying with FBI reporting standards and, thus, not compiled by the FBI, are shown as having Insufficient Data in the map. PolicyMap recommends consulting the Data Directory for more information on the data. PolicyMap last updated this data in February 2022.

    Divided the total number of violent crimes in each county by the county's population.

### Crime_rate_per_10K (Social)

#### Measure Description & Calculation


-   The crime rate per 10,000 people is calculated by taking the total number of violent crimes divided by the population times 10,000.

$$
\text{Crime\_rate\_per\_10K} = \frac{\text{Total Number of Violent Crimes}}{\text{Population}} \times 10,000
$$