---
date: "07/11/2024"
date-modified: last-modified
---

# FEMA National Risk Index {.unnumbered}

## Brief Description

The FEMA National Risk Index Dataset provides information on the annual events from various natural disasters across the United States. It is designed to help communities understand their risk levels and make informed decisions about mitigation and preparedness.

## Source

[FEMA NRI](https://hazards.fema.gov/nri/data-resources)

## Measures
We are using the Natural Hazard Annualized Frequency, which is the expected frequency or probability of a hazard occurrence per year. It takes the number of recorded hazard occurrences each year over a given period or probability of a hazard occurrence each year.

### Flood_Annual_Events (Natural)
- The annualized frequency value represents the number of Riverine Flooding Occurrences, in event-day, each year over the period of record. It is initially calculated at the county level. The NCEI Storm Events Database Riverine Flooding events for the county divided by the period of record.

### Heat_Annual_Events (Natural)
- The annualized frequency of Heat Waves in an area is estimated by the number of recorded Heat Wave occurrences, in event-days, each year over the period of record. It is calculated by the number of Heat Wave event-days that intersect the Census block divided by the period of record for Heat Wave.

### Hail_Annual_Events (Natural)
- The annualized frequency of Hail is estimated by the number of recorded Hail occurrences, in events, each years over the period of record. It is calculated by the scaled count of Hail events calculated for the Census block divdided by the period of record for Hail.

### Wind_Annual_Events (Natural)
- The annualized frequency of Strong Wind events in an area is estimated by the number of recorded Strong Wind occurrences, in events, each year over the period of record. It is calculated byt the scaled count of Strong Wind events calculated for the Census block divided by the period of record for Strong Wind.

### Tornado_Annual_Events (Natural)
- The annualized frequency of Tornado is estimated by the number of Tornado occurrences, in events, each year for a specific area. It is calculated by the count of distinct Tornado events of a sub-type that have occurred in the U.S. divided by the summed total count of all 80-km buffed Tornado-fishnet grid cell intersections of a Tornado sub-type in the U.S.

### Winter_Annual_Events (Natural)
- The annualized frequency of Winter Weather events in an area is estimated by the number of recorded Winter Weather occurrences, in event-days, each year over the period of record. It is calculated by the number of Winter Weather event-days that intersect the Census block divided by the period of record Winter Weather.

### Ice_Annual_Events (Natural)
- The annualized frequency of Ice Storm represents the estimated number of recorded Ice Storm occurrences, in event-days, each year for a specific area. It is calculated by the number of historic Ice Storm event-days calculated for the Census block divided by the period of record for Ice Storm.

### Drought_Annual_Events (Natural)
- The annualized frequency of Drought represents the number of recorded Drought occurrences, in event-days, each year over the period of record. It is calculated by the number of event-days that intersect the Census tract divided by the period of Drought.

## Measure Calculation
The measure values are taken from FEMA National Risk Index data.
