---
date: "07/11/2024"
date-modified: last-modified
editor: 
  markdown: 
    wrap: 72
---

# Homeland Infrastructure Foundation Level Data {.unnumbered}

## Brief Description

The Homeland Infrastructure Foundation Level Dataset (HIFLD) is a
comprehensive collection of geospatial data critical for infrastructure
planning and management, focusing on essential public services and
facilities. Its datasets, which are integral to the built capital,
include measures such as Cellular Towers, Colleges and Universities,
Convention Centers, Fire and Emergency Stations, Hospitals, Law
Enforcement Locations, Sports Venues, Private and Public Schools,
Community Colleges, and Child Care Centers.

## Source

[HIFLD](https://hifld-geoplatform.hub.arcgis.com/pages/hifld-open)

### Measures

- Cellular_Towers_per_10k (Built)
- College_Universities_per_10k (Built)
- Convention_Centers_per_10k (Built)
- Fire_Emergency_Stations_per_10k (Built)
- Hospitals_per_10k (Built)
- Local_Law_Enforcement_Locations_per_10k (Built)
- Sports_Venues_per_10k (Built)
- Private_Schools_per_10k (Built)
- Public_Schools_per_10k (Built)
- Community_Colleges_per_10k (Built)

### Measure Description & Calculation

All these measurements were obtained from the Homeland Infrastructure
Foundation Level Dataset, except for the childcare data, which was
sourced from the County Health Rankings Dataset. Initially, all datasets
were in geojson format so after extraction we performed a spatial join
with the ACS population data at both the city and county levels to
obtain the GEOID, population, and accurate county and city names,
ensuring each location was correctly correlated.

For the per_10k calculations, we used ACS population data, dividing the
total number of venues by the population and then multiplying by 10,000:

``` python
per10k = [
    'Cellular_Towers', 'College_Universities', 'Convention_Centers', 'Fire_Emergency_Stations',
    'Hospitals', 'Local_Law_Enforcement_Locations', 'Sports_Venues', 'Private_Schools', 'Public_Schools',
    'Community_Colleges', 'Child_Care_Centers'
]

for count in per10k:
  county[f'{count}_per_10k'] = ((county[count] / county['Population']) * 10000)
```
