---
date: "07/11/2024"
date-modified: last-modified
---

# Iowa Government Portal (iowa.gov) {.unnumbered}

## Brief Description

The dataset is a 2022 general election turnout report that we got from iowa.gov. The dastset is split up by counties and gives us statistics on the different type of voters in each county.

## Source

[Iowa Secretary of State](https://sos.iowa.gov/elections/pdf/2022/general/turnout.pdf)

County data from ACS 5-year report, 2022

## Measures

### % Total Absentee Voters (Social)

#### Measure Description & Calculation

Absentee voters are people that cast their vote remotely instead of at their polling place on election day. We calculated the percentage of absentee voters by taking the total absentee voters divided by the total amount of voters in a county.

$$
\text{\%\_Total\_Absentee\_Voters =} \frac{\text{Absentee Voters}}{\text{Total Voters}}
$$

### Total Voters per 10k (Social)

#### Measure Description & Calculation

The total voters number is calculated from election day voters + absentee voters. The Total Voter per 10,000 people is calculated by taking the proportion of total voters of a county divided by the population of the county times 10,000.

$$
\text{Total Voters per 10k} = \frac{\text{Total Voters}}{\text{Population}}\times 10000
$$

### Total Voters (18+ Citizen) per 10k (Social)

#### Measure Description & Calculation

Total voters is calculated from election day and absentee voters. The population of citizens 18+ is from the acs variable B29001_001. The Total Voters (18+ Citizen) per 10,000 people is the proportion of total voters in a county per 10,000 people that are 18+ citizens times 10,000.

$$
\text{Total Voters 18+ per 10k} = \frac{\text{Total Voters}}{\text{Population of citizens 18+}}\times 10000
$$

### Active Voters per 10k (Social)

#### Measure Description & Calculation

Active Voter per 10,000 people is the proportion of active voters as of 11/8/2022 in a county divided by the county population times 10,000.

$$
\text{Active Voters per 10,000 people} = \frac{\text{Active Voters as of 11/8/2022}}{\text{Population}}\times 10000
$$

### Election Day Voters per 10k (Social)

#### Measure Description & Calculation

Election Day Voters per 10,000 people is the proportion of election day voters in a county divided by the county population times 10,000.

$$
\text{Election Day Voters per 10,000 people} = \frac{\text{Election Day Voters}}{\text{Population}}\times 10000
$$

### Absentee Voters per 10k (Social)

#### Measure Description & Calculation

Absentee Voters per 10,000 people is the proportion of absentee voters in a county divided by county population time 10,000.

$$
\text{Absentee Voters per 10,000 people} = \frac{\text{Absentee Voters}}{\text{Population}}\times 10000
$$

### % Total Voter Turnout (Social)

#### Measure Description and Calculation

\% Total Voter Turnout is the proportion of total voters in a county divided by the registered voter population (active and inactive voters).

$$
\text{\%\_Total\_Voter\_Turnout} = \frac{\text{Total Voter}}{\text{Active Voters + Inactive Voters}}
$$
