---
date: "07/11/2024"
date-modified: last-modified
---

# Open Street Maps {.unnumbered}

## Brief Description

Open Street Map is an open data source where people can edit the map of the world. The map contains roads, trails, cafes, railroads, parks, schools, and more.

## Source

[Open Street Map](https://www.openstreetmap.org/#map=14/42.0232/-93.6291&layers=T)

[U.S. Census Bureau](https://www.census.gov/cgi-bin/geo/shapefiles/index.php)

City data from ACS 5-year report, 2022

## Measures

### Park Area (Natural)

#### Measure Description & Calculation

The land designated to parks in a city. To get the city area we had to use the sf package in r to find the area of the polygon geometries of the parks.

``` r
Final_Parks_City_intersection$park_area <- 
    st_area(st_geometry(Final_Parks_City_intersection))
```

### City Area (Natural)

#### Measure Description & Calculation

The land designated to the cities in Iowa. We got the polygon geometry for the cities from the Tiger/line Shapefile, choosing 2023 Iowa Places. We then used the sf package in r to find the area of the polygon geometries of the cities.

``` r
shape$city_area <- st_area(st_geometry(shape))
```

### Park City Proportion (Natural)

#### Measure Description & Calculation

The park area as a proportion of the total city area.

$$
\text{Park City Proportion} = \frac{\text{park area}}{\text{city area}}
$$

### Num Parks Per 10K (Natural)

#### Measure Description & Calculation

The number of parks in a city per 10,000 people.

$$
\text{Num Parks Per 10K} = \frac{\text{number of parks in a city}}{\text{Population}}\times 10000
$$
