---
title: "table-of-contents"
format: html
---

# Table of Contents

## Built
- Median household property value
- Median year of built structures
- Percentage of housing units built before 1960
- Percentage of units that are occupied
- Percentage of households with complete plumbing
- Percentage of households with a broadband subscription
- Number of bridges per acre
- Percent of bridges that are obsolete or structurally deficient
- Number of cell towers per 10,000 population
- Number of public schools per 10,000 population
- Number of private schools per 10,000 population
- Number of colleges and universities per 10,000 population
- Number of community colleges per 10,000 population
- Number of fire stations per 10,000 population
- Number of police stations per 10,000 population (Law Enforcement)
- Number of hospitals per 10,000 population
- Number of child care centers per 10,000 population
- Number of convention centers per 10,000 population
- Number of sports venues per 10,000 population
- Food Environment Index
- Power plant energy generation


## Cultural
- Cultural Locations per 10,000 population (Historic sites, public art, museums, monuments)
- Racial Diversity Simpson Index
- Religious Diversity Simpson Index
- Library Visits per 10,000 population
- Library Book Circulation per 10,000 population
- Community Events per 10,000 population


## Financial
- County GDP per Capita (Thousands of $)
- Percent of County GDP in Manufacturing
- Percent of County GDP in Finance & Insurance
- Unemployment rate among 16+ population
- Percent of 16+ Population in Labor Force
- Percent of 20-64 Population in Labor Force
- Median Household Income
- Percent of households below poverty line
- Gini Index of Income Diversity
- Percent of total businesses that are small (<=4 employees)

## Human
- Percent of adults with fair or poor health
- Poor physical health days (average number of physically unhealthy days in last 30)
- Poor mental health days (average number of mentally unhealthy days in last 30)
- Health insurance rate (civilian noninstitutionalized population)
- Percent of 25+ Population with Bachelor's Degree
- Percent of 25+ Population with HS Degree
- Senior dependency ratio (ratio of 65+ population to 18-64 population)
- Child dependency ratio (ratio of <18 population to 18-64 population)
- Dependency Ratio (ratio of children and seniors to 18-64 population)


## Natural
- Percent of County in Cropland
- Cropland Value in Dollards per Acre
- Percent of County in Forest Reserve Program
- Percent of County in Public Areas
- City Parks per 10,000 Population
- Total Length of Streams in County
- Percent of County in Lakes
- Percent of County in Wetlands
- Presence of Drinking Water Violations
- Particulate Matter (PM2.5) Density
- Air toxics cancer risk
- Respiratory Hazard Index
- Toxic releases to air
- Weighted proximity to hazardous waste
- Weighted proximity to wastewater discharge
- Percent of County GDP in Agriculture, Forestry, Fishing, and Hunting
- Percent of County GDP in Mining
- Percent of population employed in agriculture, forestry, fishing and hunting, and mining
- Annualized frequency of floods
- Annualized frequency of heat waves
- Annualized frequency of hail
- Annualized frequency of strong wind
- Annualized frequency of tornadoes
- Annualized frequency of winter weather
- Annualized frequency of ice storms
- Annualized frequency of droughts


## Political
- Federal election contributions
- State election contributions


## Social
- Violent Crime per 10,000 Population
- Total crime per 10,000 Population
- Economic Connectedness
- Cohesiveness (Support Ratio)
- Clustering - Percent of friends that are also friends with each other
- Volunteering Rate
- Civic Organizations
- Percent of single-parent households with children
- Percent of female-headed single-parent households with children
- Percent of male-headed single-parent households with children
- Percent of Workers with more than an hour commute
- Percent of Residents who are not proficient at English
- 2020 Decennial Respondent Rates
- Percent Voter Turnout
- Total Voters per 10,000 Population
- School Violence per 1,000 students